Cora:
  learning_rate: 0.0005
  num_hidden: 128
  num_proj_hidden: 128
  activation: 'relu'
  base_model: 'GCNConv'
  num_layers: 2
  drop_edge_rate_1: 0.2
  drop_edge_rate_2: 0.4
  drop_feature_rate_1: 0.3
  drop_feature_rate_2: 0.4
  tau: 0.4
  t1: 0.7
  t2: 0.3
  alpha: 0.7
  beta: 0.7
  num_epochs: 300
  weight_decay: 0.00001
CiteSeer:
  learning_rate: 0.001
  num_hidden: 128
  num_proj_hidden: 128
  activation: 'prelu'
  base_model: 'GCNConv'
  num_layers: 2
  drop_edge_rate_1: 0.2
  drop_edge_rate_2: 0.4
  drop_feature_rate_1: 0.3
  drop_feature_rate_2: 0.4
  tau: 0.5
  t1: 0.7
  t2: 0.3
  alpha: 0.7
  beta: 0.7
  num_epochs: 150
  weight_decay: 0.00001
PubMed:
  learning_rate: 0.001
  num_hidden: 256
  num_proj_hidden: 256
  activation: 'relu'
  base_model: 'GCNConv'
  num_layers: 2
  drop_edge_rate_1: 0.4
  drop_edge_rate_2: 0.1
  drop_feature_rate_1: 0.0
  drop_feature_rate_2: 0.2
  tau: 0.7
  t1: 0.7
  t2: 0.3
  alpha: 0.7
  beta: 0.7
  num_epochs: 170
  weight_decay: 0.00001
photo:
  learning_rate: 0.0005
  num_hidden: 256
  num_proj_hidden: 128
  activation: 'relu'
  base_model: 'GCNConv'
  num_layers: 2
  drop_edge_rate_1: 0.0
  drop_edge_rate_2: 0.5
  drop_feature_rate_1: 0.1
  drop_feature_rate_2: 0.0
  tau: 0.9
  t1: 0.8
  t2: 0.2
  alpha: 0.9
  beta: 0.9
  num_epochs: 200
  weight_decay: 0.00001